// Build-based skill guides: median skill levels of competent players (won or
// 2+ runes) per build, by XL milestone. Source: crawl.dcss.io 0.34 logfile,
// derived from replay (ttyrec) skill snapshots; `n` = sample size per build.
// Generated by /tmp/regen-guides.py (slice + growing full dataset, merged).

export interface BuildGuide { n: number; milestones: Record<string, Record<string, number>> }

export const BUILD_GUIDES: Record<string, BuildGuide> = {
  "Minotaur/Fighter": {
    "n": 24,
    "milestones": {
      "1": {
        "Fighting": 3.6,
        "Armour": 3.6,
        "Shields": 3.6,
        "Axes": 2.4,
        "Maces & Flails": 1.3,
        "Polearms": 1.3
      },
      "3": {
        "Fighting": 3.6,
        "Armour": 3.6,
        "Shields": 3.6,
        "Axes": 2.4,
        "Maces & Flails": 1.3,
        "Polearms": 1.3
      },
      "5": {
        "Fighting": 3.6,
        "Armour": 3.6,
        "Shields": 3.6,
        "Axes": 2.4,
        "Maces & Flails": 1.3,
        "Polearms": 1.3
      },
      "7": {
        "Fighting": 3.6,
        "Armour": 3.6,
        "Shields": 3.6,
        "Axes": 3.0,
        "Maces & Flails": 2.5,
        "Polearms": 1.8
      },
      "9": {
        "Axes": 7.3,
        "Polearms": 5.1,
        "Maces & Flails": 4.6,
        "Fighting": 4.5,
        "Armour": 4.0,
        "Shields": 3.6
      },
      "12": {
        "Axes": 12.2,
        "Fighting": 9.9,
        "Armour": 9.1,
        "Polearms": 9.0,
        "Maces & Flails": 8.1,
        "Shields": 6.5
      },
      "15": {
        "Axes": 15.7,
        "Fighting": 11.7,
        "Polearms": 10.3,
        "Shields": 10.3,
        "Armour": 10.2,
        "Maces & Flails": 10.1
      },
      "18": {
        "Axes": 15.8,
        "Fighting": 14.1,
        "Armour": 11.2,
        "Shields": 11.1,
        "Polearms": 10.4,
        "Maces & Flails": 10.2
      },
      "21": {
        "Axes": 16.1,
        "Fighting": 14.1,
        "Armour": 11.2,
        "Shields": 11.1,
        "Polearms": 10.4,
        "Maces & Flails": 10.2
      },
      "27": {
        "Axes": 16.1,
        "Fighting": 14.1,
        "Armour": 11.2,
        "Shields": 11.1,
        "Polearms": 10.4,
        "Maces & Flails": 10.2
      }
    }
  },
  "Minotaur/Berserker": {
    "n": 25,
    "milestones": {
      "1": {
        "Fighting": 3.6,
        "Axes": 3.6,
        "Armour": 2.4,
        "Maces & Flails": 2.1,
        "Polearms": 2.1,
        "Dodging": 2.1
      },
      "3": {
        "Fighting": 3.6,
        "Axes": 3.6,
        "Armour": 2.4,
        "Maces & Flails": 2.1,
        "Polearms": 2.1,
        "Dodging": 2.1
      },
      "5": {
        "Fighting": 4.2,
        "Axes": 4.0,
        "Maces & Flails": 2.4,
        "Polearms": 2.4,
        "Armour": 2.4,
        "Dodging": 2.1
      },
      "7": {
        "Axes": 5.8,
        "Fighting": 4.7,
        "Maces & Flails": 3.5,
        "Polearms": 3.3,
        "Armour": 2.4,
        "Dodging": 2.1
      },
      "9": {
        "Axes": 7.2,
        "Fighting": 6.0,
        "Maces & Flails": 4.3,
        "Polearms": 4.0,
        "Armour": 3.0,
        "Dodging": 2.1
      },
      "12": {
        "Fighting": 12.0,
        "Axes": 11.4,
        "Polearms": 9.0,
        "Maces & Flails": 8.6,
        "Armour": 7.1,
        "Shields": 5.2
      },
      "15": {
        "Fighting": 15.0,
        "Axes": 14.4,
        "Armour": 12.0,
        "Polearms": 10.3,
        "Maces & Flails": 10.2,
        "Shields": 10.1
      },
      "18": {
        "Fighting": 15.4,
        "Axes": 15.2,
        "Armour": 15.0,
        "Shields": 12.8,
        "Polearms": 10.4,
        "Maces & Flails": 10.3
      },
      "21": {
        "Armour": 16.1,
        "Axes": 15.2,
        "Fighting": 15.0,
        "Shields": 14.4,
        "Polearms": 10.4,
        "Maces & Flails": 10.3
      },
      "27": {
        "Axes": 15.2,
        "Armour": 15.0,
        "Shields": 14.4,
        "Fighting": 12.0,
        "Polearms": 11.0,
        "Maces & Flails": 10.4
      }
    }
  },
  "Gargoyle/Fighter": {
    "n": 20,
    "milestones": {
      "1": {
        "Fighting": 3.2,
        "Armour": 3.2,
        "Shields": 3.2,
        "Maces & Flails": 2.0,
        "Staves": 1.1,
        "Axes": 1.0
      },
      "3": {
        "Fighting": 3.5,
        "Armour": 3.4,
        "Shields": 3.3,
        "Maces & Flails": 1.8,
        "Axes": 1.5,
        "Polearms": 1.3
      },
      "5": {
        "Armour": 3.7,
        "Fighting": 3.6,
        "Shields": 3.4,
        "Maces & Flails": 2.2,
        "Axes": 1.8,
        "Polearms": 1.4
      },
      "7": {
        "Fighting": 4.2,
        "Armour": 4.2,
        "Shields": 3.6,
        "Maces & Flails": 3.0,
        "Axes": 2.3,
        "Staves": 1.6
      },
      "9": {
        "Fighting": 5.6,
        "Armour": 5.4,
        "Shields": 4.5,
        "Maces & Flails": 4.1,
        "Axes": 3.0,
        "Polearms": 2.5
      },
      "12": {
        "Fighting": 9.7,
        "Armour": 9.2,
        "Maces & Flails": 6.5,
        "Shields": 5.9,
        "Polearms": 5.2,
        "Axes": 4.8
      },
      "15": {
        "Fighting": 11.9,
        "Armour": 10.6,
        "Shields": 9.2,
        "Invocations": 7.5,
        "Maces & Flails": 7.1,
        "Axes": 6.9
      },
      "18": {
        "Fighting": 12.6,
        "Armour": 10.6,
        "Shields": 9.2,
        "Maces & Flails": 8.5,
        "Axes": 8.1,
        "Invocations": 8.0
      },
      "21": {
        "Fighting": 12.6,
        "Armour": 10.6,
        "Shields": 9.2,
        "Maces & Flails": 8.7,
        "Axes": 8.1,
        "Invocations": 8.0
      },
      "27": {
        "Fighting": 12.0,
        "Armour": 10.6,
        "Shields": 9.2,
        "Maces & Flails": 8.7,
        "Axes": 8.1,
        "Invocations": 8.0
      }
    }
  },
  "Coglin/Hunter": {
    "n": 25,
    "milestones": {
      "1": {
        "Ranged Weapons": 3.6,
        "Fighting": 2.0,
        "Dodging": 1.7,
        "Stealth": 0.7,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "3": {
        "Ranged Weapons": 3.6,
        "Fighting": 2.0,
        "Dodging": 1.7,
        "Stealth": 0.7,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "5": {
        "Ranged Weapons": 3.6,
        "Fighting": 2.0,
        "Dodging": 1.7,
        "Stealth": 0.7,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "7": {
        "Ranged Weapons": 4.3,
        "Fighting": 2.0,
        "Dodging": 1.7,
        "Stealth": 0.7,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "9": {
        "Ranged Weapons": 7.3,
        "Fighting": 4.3,
        "Dodging": 1.7,
        "Stealth": 0.7,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "12": {
        "Ranged Weapons": 10.2,
        "Fighting": 8.1,
        "Dodging": 5.6,
        "Evocations": 1.0,
        "Stealth": 0.7,
        "Armour": 0.4
      },
      "15": {
        "Ranged Weapons": 12.4,
        "Fighting": 11.4,
        "Dodging": 6.6,
        "Evocations": 5.5,
        "Invocations": 5.0,
        "Armour": 4.6
      },
      "18": {
        "Ranged Weapons": 13.8,
        "Fighting": 12.5,
        "Dodging": 9.4,
        "Evocations": 8.0,
        "Invocations": 6.0,
        "Armour": 5.8
      },
      "21": {
        "Fighting": 12.5,
        "Ranged Weapons": 12.4,
        "Dodging": 9.7,
        "Evocations": 8.0,
        "Invocations": 6.0,
        "Armour": 5.8
      },
      "27": {
        "Fighting": 12.5,
        "Ranged Weapons": 12.4,
        "Dodging": 9.7,
        "Evocations": 8.0,
        "Invocations": 6.0,
        "Armour": 5.8
      }
    }
  },
  "Gargoyle/Earth Elementalist": {
    "n": 12,
    "milestones": {
      "1": {
        "Earth Magic": 3.6,
        "Stealth": 2.1,
        "Spellcasting": 2.0,
        "Dodging": 1.5,
        "Conjurations": 1.1,
        "Fighting": 0.0
      },
      "3": {
        "Earth Magic": 4.0,
        "Stealth": 2.1,
        "Spellcasting": 2.0,
        "Dodging": 1.5,
        "Conjurations": 1.1,
        "Fighting": 0.0
      },
      "5": {
        "Earth Magic": 4.5,
        "Stealth": 2.1,
        "Spellcasting": 2.0,
        "Conjurations": 2.0,
        "Dodging": 1.5,
        "Fighting": 0.0
      },
      "7": {
        "Earth Magic": 6.0,
        "Conjurations": 4.2,
        "Spellcasting": 3.4,
        "Stealth": 2.1,
        "Fighting": 2.0,
        "Dodging": 1.5
      },
      "9": {
        "Earth Magic": 9.6,
        "Spellcasting": 6.0,
        "Conjurations": 6.0,
        "Fighting": 3.0,
        "Stealth": 2.5,
        "Dodging": 1.5
      },
      "12": {
        "Spellcasting": 10.0,
        "Earth Magic": 9.8,
        "Conjurations": 6.8,
        "Fighting": 6.1,
        "Ice Magic": 4.0,
        "Translocations": 3.0
      },
      "15": {
        "Earth Magic": 12.3,
        "Spellcasting": 11.6,
        "Fighting": 9.0,
        "Conjurations": 8.4,
        "Ice Magic": 4.0,
        "Stealth": 3.3
      },
      "18": {
        "Spellcasting": 12.9,
        "Earth Magic": 12.7,
        "Fighting": 9.3,
        "Conjurations": 8.4,
        "Ice Magic": 4.0,
        "Stealth": 3.3
      },
      "21": {
        "Spellcasting": 12.9,
        "Earth Magic": 12.7,
        "Fighting": 11.0,
        "Conjurations": 8.4,
        "Ice Magic": 4.0,
        "Stealth": 3.3
      },
      "27": {
        "Earth Magic": 14.7,
        "Spellcasting": 12.9,
        "Fighting": 11.0,
        "Conjurations": 9.9,
        "Shields": 5.0,
        "Stealth": 3.3
      }
    }
  },
  "Troll/Fighter": {
    "n": 19,
    "milestones": {
      "1": {
        "Shields": 2.6,
        "Fighting": 2.4,
        "Dodging": 2.4,
        "Unarmed Combat": 2.0,
        "Spellcasting": 0.0,
        "Armour": 0.0
      },
      "3": {
        "Shields": 2.6,
        "Fighting": 2.4,
        "Dodging": 2.4,
        "Unarmed Combat": 2.0,
        "Spellcasting": 0.0,
        "Armour": 0.0
      },
      "5": {
        "Shields": 2.6,
        "Fighting": 2.4,
        "Dodging": 2.4,
        "Unarmed Combat": 2.3,
        "Spellcasting": 0.0,
        "Armour": 0.0
      },
      "7": {
        "Shields": 2.8,
        "Fighting": 2.5,
        "Dodging": 2.4,
        "Unarmed Combat": 2.3,
        "Spellcasting": 0.0,
        "Armour": 0.0
      },
      "9": {
        "Unarmed Combat": 5.9,
        "Fighting": 5.0,
        "Shields": 3.6,
        "Dodging": 2.5,
        "Spellcasting": 0.0,
        "Armour": 0.0
      },
      "12": {
        "Unarmed Combat": 10.2,
        "Fighting": 7.2,
        "Throwing": 5.4,
        "Shields": 4.1,
        "Dodging": 3.0,
        "Spellcasting": 0.0
      },
      "15": {
        "Unarmed Combat": 10.7,
        "Fighting": 8.1,
        "Throwing": 6.0,
        "Shields": 5.8,
        "Dodging": 3.0,
        "Invocations": 2.5
      },
      "18": {
        "Unarmed Combat": 10.7,
        "Fighting": 8.1,
        "Shields": 7.0,
        "Throwing": 6.0,
        "Dodging": 3.0,
        "Invocations": 2.5
      },
      "21": {
        "Unarmed Combat": 10.7,
        "Fighting": 8.1,
        "Shields": 7.0,
        "Throwing": 6.0,
        "Dodging": 3.0,
        "Invocations": 2.5
      },
      "27": {
        "Unarmed Combat": 10.7,
        "Fighting": 8.1,
        "Shields": 7.0,
        "Throwing": 6.0,
        "Dodging": 3.0,
        "Invocations": 2.5
      }
    }
  },
  "Demonspawn/Fighter": {
    "n": 12,
    "milestones": {
      "1": {
        "Fighting": 3.0,
        "Armour": 2.6,
        "Shields": 2.6,
        "Axes": 1.7,
        "Maces & Flails": 1.0,
        "Polearms": 1.0
      },
      "3": {
        "Fighting": 3.0,
        "Armour": 2.6,
        "Shields": 2.6,
        "Axes": 1.8,
        "Maces & Flails": 1.1,
        "Polearms": 1.0
      },
      "5": {
        "Fighting": 3.1,
        "Armour": 2.8,
        "Shields": 2.8,
        "Axes": 2.2,
        "Maces & Flails": 1.4,
        "Polearms": 1.4
      },
      "7": {
        "Fighting": 3.5,
        "Armour": 3.0,
        "Shields": 3.0,
        "Axes": 2.5,
        "Maces & Flails": 1.9,
        "Polearms": 1.8
      },
      "9": {
        "Fighting": 3.5,
        "Armour": 3.1,
        "Shields": 3.0,
        "Axes": 2.5,
        "Maces & Flails": 2.0,
        "Polearms": 2.0
      },
      "12": {
        "Axes": 9.4,
        "Fighting": 8.4,
        "Armour": 7.7,
        "Shields": 7.3,
        "Invocations": 6.5,
        "Maces & Flails": 6.2
      },
      "15": {
        "Axes": 12.6,
        "Fighting": 11.2,
        "Armour": 10.8,
        "Shields": 9.8,
        "Maces & Flails": 9.2,
        "Polearms": 9.2
      },
      "18": {
        "Axes": 15.0,
        "Fighting": 13.2,
        "Armour": 12.7,
        "Shields": 11.8,
        "Maces & Flails": 10.1,
        "Polearms": 9.8
      },
      "21": {
        "Axes": 15.0,
        "Fighting": 13.8,
        "Armour": 13.1,
        "Shields": 12.0,
        "Maces & Flails": 10.1,
        "Polearms": 9.8
      },
      "27": {
        "Axes": 15.0,
        "Fighting": 13.8,
        "Armour": 13.1,
        "Shields": 12.0,
        "Maces & Flails": 10.1,
        "Polearms": 9.8
      }
    }
  },
  "Formicid/Hunter": {
    "n": 9,
    "milestones": {
      "1": {
        "Ranged Weapons": 4.0,
        "Fighting": 2.1,
        "Dodging": 1.7,
        "Stealth": 1.2,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "3": {
        "Ranged Weapons": 4.0,
        "Fighting": 2.1,
        "Dodging": 1.7,
        "Stealth": 1.2,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "5": {
        "Ranged Weapons": 4.6,
        "Fighting": 2.1,
        "Dodging": 1.7,
        "Stealth": 1.2,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "7": {
        "Ranged Weapons": 6.9,
        "Fighting": 2.9,
        "Dodging": 1.7,
        "Stealth": 1.2,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "9": {
        "Ranged Weapons": 8.7,
        "Fighting": 4.5,
        "Shields": 3.4,
        "Dodging": 1.8,
        "Stealth": 1.2,
        "Invocations": 0.2
      },
      "12": {
        "Ranged Weapons": 12.9,
        "Fighting": 9.0,
        "Shields": 6.8,
        "Dodging": 6.3,
        "Invocations": 5.5,
        "Armour": 5.0
      },
      "15": {
        "Ranged Weapons": 15.7,
        "Fighting": 10.8,
        "Invocations": 10.2,
        "Shields": 10.1,
        "Armour": 8.2,
        "Dodging": 7.5
      },
      "18": {
        "Ranged Weapons": 18.0,
        "Fighting": 15.0,
        "Shields": 10.6,
        "Invocations": 10.2,
        "Armour": 10.0,
        "Dodging": 10.0
      },
      "21": {
        "Ranged Weapons": 18.0,
        "Fighting": 15.0,
        "Shields": 15.0,
        "Armour": 14.5,
        "Invocations": 10.2,
        "Dodging": 10.0
      },
      "27": {
        "Ranged Weapons": 18.0,
        "Shields": 15.0,
        "Armour": 14.5,
        "Fighting": 13.6,
        "Invocations": 10.2,
        "Dodging": 10.0
      }
    }
  },
  "Human/Conjurer": {
    "n": 9,
    "milestones": {
      "1": {
        "Conjurations": 4.0,
        "Spellcasting": 2.0,
        "Dodging": 2.0,
        "Stealth": 2.0,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "3": {
        "Conjurations": 4.0,
        "Spellcasting": 2.0,
        "Dodging": 2.0,
        "Stealth": 2.0,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "5": {
        "Conjurations": 5.2,
        "Spellcasting": 4.0,
        "Dodging": 2.0,
        "Stealth": 2.0,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "7": {
        "Conjurations": 7.3,
        "Spellcasting": 4.0,
        "Translocations": 2.0,
        "Dodging": 2.0,
        "Stealth": 2.0,
        "Alchemy": 1.9
      },
      "9": {
        "Conjurations": 9.0,
        "Alchemy": 5.5,
        "Spellcasting": 5.0,
        "Translocations": 4.0,
        "Invocations": 4.0,
        "Dodging": 2.0
      },
      "12": {
        "Conjurations": 10.0,
        "Spellcasting": 6.0,
        "Alchemy": 6.0,
        "Invocations": 6.0,
        "Translocations": 5.0,
        "Dodging": 2.0
      },
      "15": {
        "Conjurations": 10.0,
        "Invocations": 9.0,
        "Spellcasting": 6.0,
        "Translocations": 5.0,
        "Alchemy": 5.0,
        "Dodging": 2.0
      },
      "18": {
        "Conjurations": 10.0,
        "Invocations": 9.0,
        "Spellcasting": 6.0,
        "Translocations": 5.0,
        "Alchemy": 5.0,
        "Dodging": 2.0
      },
      "21": {
        "Conjurations": 10.0,
        "Invocations": 9.0,
        "Spellcasting": 6.0,
        "Translocations": 5.0,
        "Alchemy": 5.0,
        "Dodging": 2.0
      },
      "27": {
        "Conjurations": 10.0,
        "Invocations": 9.0,
        "Spellcasting": 6.0,
        "Translocations": 5.0,
        "Alchemy": 5.0,
        "Dodging": 2.0
      }
    }
  },
  "Minotaur/Shapeshifter": {
    "n": 8,
    "milestones": {
      "1": {
        "Unarmed Combat": 3.2,
        "Fighting": 2.4,
        "Shapeshifting": 2.4,
        "Dodging": 2.1,
        "Spellcasting": 0.0,
        "Armour": 0.0
      },
      "3": {
        "Fighting": 3.8,
        "Unarmed Combat": 3.2,
        "Shapeshifting": 2.4,
        "Dodging": 2.1,
        "Maces & Flails": 0.8,
        "Spellcasting": 0.0
      },
      "5": {
        "Fighting": 4.8,
        "Unarmed Combat": 3.2,
        "Axes": 3.0,
        "Shapeshifting": 2.4,
        "Dodging": 2.1,
        "Maces & Flails": 2.0
      },
      "7": {
        "Fighting": 5.2,
        "Axes": 3.3,
        "Unarmed Combat": 3.2,
        "Shapeshifting": 2.4,
        "Maces & Flails": 2.1,
        "Dodging": 2.1
      },
      "9": {
        "Fighting": 7.8,
        "Axes": 6.2,
        "Armour": 5.8,
        "Maces & Flails": 5.6,
        "Polearms": 3.5,
        "Unarmed Combat": 3.2
      },
      "12": {
        "Axes": 14.6,
        "Maces & Flails": 10.5,
        "Armour": 10.1,
        "Fighting": 9.9,
        "Polearms": 8.5,
        "Shields": 6.0
      },
      "15": {
        "Axes": 18.0,
        "Fighting": 14.6,
        "Armour": 13.6,
        "Shields": 12.3,
        "Maces & Flails": 11.7,
        "Polearms": 11.0
      },
      "18": {
        "Axes": 18.0,
        "Fighting": 16.2,
        "Armour": 14.7,
        "Shields": 14.0,
        "Maces & Flails": 11.7,
        "Polearms": 11.0
      },
      "21": {
        "Axes": 18.0,
        "Fighting": 17.8,
        "Armour": 17.4,
        "Shields": 16.2,
        "Maces & Flails": 12.2,
        "Polearms": 11.0
      },
      "27": {
        "Axes": 18.0,
        "Fighting": 17.8,
        "Armour": 17.4,
        "Shields": 17.2,
        "Maces & Flails": 13.9,
        "Dodging": 11.5
      }
    }
  },
  "Mummy/Necromancer": {
    "n": 7,
    "milestones": {
      "1": {
        "Necromancy": 4.0,
        "Spellcasting": 2.6,
        "Dodging": 1.5,
        "Stealth": 1.5,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "3": {
        "Necromancy": 4.0,
        "Spellcasting": 2.6,
        "Dodging": 1.5,
        "Stealth": 1.5,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "5": {
        "Necromancy": 4.0,
        "Spellcasting": 2.6,
        "Dodging": 1.5,
        "Stealth": 1.5,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "7": {
        "Spellcasting": 6.5,
        "Necromancy": 6.0,
        "Fighting": 2.9,
        "Dodging": 2.0,
        "Stealth": 2.0,
        "Unarmed Combat": 0.0
      },
      "9": {
        "Spellcasting": 9.0,
        "Necromancy": 6.0,
        "Fighting": 5.0,
        "Dodging": 4.0,
        "Stealth": 2.0,
        "Unarmed Combat": 0.0
      },
      "12": {
        "Spellcasting": 11.0,
        "Fighting": 9.0,
        "Dodging": 7.0,
        "Necromancy": 6.0,
        "Conjurations": 4.0,
        "Earth Magic": 2.7
      },
      "15": {
        "Spellcasting": 12.0,
        "Fighting": 11.0,
        "Dodging": 9.0,
        "Conjurations": 8.0,
        "Necromancy": 6.4,
        "Air Magic": 4.5
      },
      "18": {
        "Spellcasting": 12.0,
        "Fighting": 11.0,
        "Dodging": 9.0,
        "Conjurations": 8.0,
        "Necromancy": 6.4,
        "Air Magic": 4.5
      },
      "21": {
        "Spellcasting": 12.0,
        "Fighting": 11.0,
        "Dodging": 9.0,
        "Conjurations": 8.0,
        "Necromancy": 6.4,
        "Air Magic": 4.5
      },
      "27": {
        "Spellcasting": 12.0,
        "Fighting": 11.0,
        "Dodging": 9.0,
        "Conjurations": 8.0,
        "Necromancy": 6.4,
        "Air Magic": 4.5
      }
    }
  },
  "Demonspawn/Necromancer": {
    "n": 7,
    "milestones": {
      "1": {
        "Necromancy": 4.3,
        "Spellcasting": 2.0,
        "Dodging": 1.7,
        "Stealth": 1.7,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "3": {
        "Necromancy": 4.3,
        "Spellcasting": 2.0,
        "Stealth": 1.8,
        "Dodging": 1.7,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "5": {
        "Necromancy": 5.7,
        "Spellcasting": 3.2,
        "Stealth": 2.0,
        "Dodging": 1.7,
        "Fighting": 0.0,
        "Polearms": 0.0
      },
      "7": {
        "Necromancy": 6.4,
        "Spellcasting": 4.0,
        "Stealth": 2.0,
        "Dodging": 1.7,
        "Fighting": 0.0,
        "Polearms": 0.0
      },
      "9": {
        "Necromancy": 9.1,
        "Spellcasting": 7.4,
        "Stealth": 3.0,
        "Dodging": 2.7,
        "Axes": 2.2,
        "Long Blades": 1.1
      },
      "12": {
        "Necromancy": 10.9,
        "Spellcasting": 9.4,
        "Armour": 6.8,
        "Fighting": 6.0,
        "Stealth": 3.2,
        "Dodging": 2.8
      },
      "15": {
        "Fighting": 12.3,
        "Necromancy": 12.3,
        "Spellcasting": 10.1,
        "Armour": 9.1,
        "Polearms": 4.9,
        "Dodging": 4.0
      },
      "18": {
        "Spellcasting": 13.7,
        "Ranged Weapons": 13.4,
        "Necromancy": 13.3,
        "Fighting": 12.3,
        "Armour": 11.3,
        "Shields": 8.2
      },
      "21": {
        "Ranged Weapons": 18.0,
        "Spellcasting": 13.9,
        "Necromancy": 13.3,
        "Fighting": 12.6,
        "Armour": 11.6,
        "Dodging": 9.7
      },
      "27": {
        "Ranged Weapons": 18.0,
        "Spellcasting": 15.3,
        "Necromancy": 14.7,
        "Fighting": 14.5,
        "Armour": 14.1,
        "Dodging": 9.7
      }
    }
  },
  "Tengu/Air Elementalist": {
    "n": 6,
    "milestones": {
      "1": {
        "Air Magic": 4.0,
        "Dodging": 2.1,
        "Spellcasting": 2.0,
        "Stealth": 2.0,
        "Conjurations": 1.3,
        "Fighting": 0.0
      },
      "3": {
        "Air Magic": 4.0,
        "Dodging": 2.1,
        "Spellcasting": 2.0,
        "Stealth": 2.0,
        "Conjurations": 1.3,
        "Fighting": 0.0
      },
      "5": {
        "Air Magic": 4.5,
        "Spellcasting": 2.5,
        "Dodging": 2.1,
        "Stealth": 2.0,
        "Conjurations": 1.3,
        "Fighting": 0.0
      },
      "7": {
        "Air Magic": 7.2,
        "Spellcasting": 3.8,
        "Conjurations": 2.5,
        "Dodging": 2.1,
        "Stealth": 2.0,
        "Fighting": 0.0
      },
      "9": {
        "Air Magic": 10.6,
        "Spellcasting": 5.2,
        "Fighting": 3.8,
        "Conjurations": 3.5,
        "Dodging": 2.1,
        "Stealth": 2.0
      },
      "12": {
        "Air Magic": 12.9,
        "Spellcasting": 7.7,
        "Fighting": 7.5,
        "Conjurations": 7.0,
        "Armour": 6.0,
        "Shields": 5.0
      },
      "15": {
        "Air Magic": 14.6,
        "Conjurations": 11.8,
        "Spellcasting": 11.1,
        "Fighting": 9.2,
        "Armour": 9.0,
        "Dodging": 5.6
      },
      "18": {
        "Air Magic": 15.6,
        "Conjurations": 14.1,
        "Spellcasting": 11.9,
        "Fighting": 11.4,
        "Armour": 9.0,
        "Shields": 7.0
      },
      "21": {
        "Air Magic": 15.6,
        "Conjurations": 15.4,
        "Spellcasting": 13.2,
        "Fighting": 11.5,
        "Armour": 10.2,
        "Shields": 8.9
      },
      "27": {
        "Conjurations": 15.9,
        "Air Magic": 14.6,
        "Spellcasting": 13.3,
        "Fighting": 12.4,
        "Armour": 10.2,
        "Shields": 8.9
      }
    }
  },
  "Armataur/Conjurer": {
    "n": 6,
    "milestones": {
      "1": {
        "Conjurations": 3.6,
        "Stealth": 2.2,
        "Spellcasting": 1.7,
        "Dodging": 1.3,
        "Fighting": 0.3,
        "Unarmed Combat": 0.0
      },
      "3": {
        "Conjurations": 4.0,
        "Stealth": 2.3,
        "Spellcasting": 1.8,
        "Dodging": 1.4,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "5": {
        "Conjurations": 6.0,
        "Stealth": 2.3,
        "Spellcasting": 1.9,
        "Dodging": 1.4,
        "Fighting": 0.0,
        "Maces & Flails": 0.0
      },
      "7": {
        "Conjurations": 6.0,
        "Translocations": 5.6,
        "Stealth": 3.0,
        "Spellcasting": 2.0,
        "Dodging": 1.7,
        "Fighting": 0.0
      },
      "9": {
        "Translocations": 9.5,
        "Conjurations": 8.0,
        "Spellcasting": 4.0,
        "Stealth": 3.0,
        "Dodging": 2.0,
        "Evocations": 1.5
      },
      "12": {
        "Translocations": 12.0,
        "Conjurations": 10.0,
        "Fighting": 8.0,
        "Armour": 5.9,
        "Alchemy": 5.9,
        "Spellcasting": 5.5
      },
      "15": {
        "Translocations": 12.0,
        "Conjurations": 10.8,
        "Fighting": 10.1,
        "Spellcasting": 9.0,
        "Armour": 8.2,
        "Alchemy": 7.2
      },
      "18": {
        "Conjurations": 14.0,
        "Translocations": 12.0,
        "Fighting": 11.6,
        "Armour": 10.7,
        "Spellcasting": 9.4,
        "Alchemy": 8.0
      },
      "21": {
        "Conjurations": 14.0,
        "Fighting": 13.0,
        "Translocations": 12.0,
        "Armour": 12.0,
        "Spellcasting": 9.4,
        "Alchemy": 8.0
      },
      "27": {
        "Conjurations": 14.0,
        "Fighting": 13.0,
        "Translocations": 12.0,
        "Armour": 12.0,
        "Spellcasting": 9.4,
        "Alchemy": 8.0
      }
    }
  },
  "Octopode/Conjurer": {
    "n": 5,
    "milestones": {
      "1": {
        "Conjurations": 4.0,
        "Stealth": 2.6,
        "Spellcasting": 2.0,
        "Dodging": 2.0,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "3": {
        "Conjurations": 4.0,
        "Stealth": 2.6,
        "Spellcasting": 2.0,
        "Dodging": 2.0,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "5": {
        "Conjurations": 5.4,
        "Stealth": 2.6,
        "Shapeshifting": 2.5,
        "Spellcasting": 2.0,
        "Dodging": 2.0,
        "Alchemy": 1.9
      },
      "7": {
        "Conjurations": 6.2,
        "Stealth": 2.6,
        "Spellcasting": 2.0,
        "Dodging": 2.0,
        "Alchemy": 1.9,
        "Fire Magic": 1.5
      },
      "9": {
        "Conjurations": 9.4,
        "Spellcasting": 3.0,
        "Stealth": 2.6,
        "Dodging": 2.0,
        "Shields": 1.2,
        "Alchemy": 0.5
      },
      "12": {
        "Conjurations": 13.0,
        "Spellcasting": 7.2,
        "Dodging": 7.1,
        "Shields": 4.9,
        "Stealth": 2.6,
        "Fighting": 0.0
      },
      "15": {
        "Conjurations": 13.9,
        "Dodging": 7.6,
        "Spellcasting": 7.2,
        "Shields": 3.1,
        "Stealth": 2.6,
        "Translocations": 2.0
      },
      "18": {
        "Conjurations": 13.9,
        "Dodging": 7.6,
        "Spellcasting": 7.2,
        "Shields": 6.3,
        "Earth Magic": 5.3,
        "Stealth": 2.6
      },
      "21": {
        "Conjurations": 13.9,
        "Dodging": 7.6,
        "Spellcasting": 7.2,
        "Shields": 6.3,
        "Earth Magic": 6.3,
        "Stealth": 2.6
      },
      "27": {
        "Conjurations": 13.9,
        "Dodging": 7.6,
        "Spellcasting": 7.2,
        "Shields": 6.3,
        "Earth Magic": 6.3,
        "Stealth": 2.6
      }
    }
  },
  "Octopode/Monk": {
    "n": 4,
    "milestones": {
      "1": {
        "Fighting": 3.0,
        "Short Blades": 3.0,
        "Dodging": 3.0,
        "Long Blades": 1.7,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "3": {
        "Fighting": 3.0,
        "Short Blades": 3.0,
        "Dodging": 3.0,
        "Long Blades": 1.7,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "5": {
        "Fighting": 3.0,
        "Short Blades": 3.0,
        "Dodging": 3.0,
        "Long Blades": 1.7,
        "Spellcasting": 0.0,
        "Unarmed Combat": 0.0
      },
      "7": {
        "Short Blades": 3.5,
        "Dodging": 3.2,
        "Fighting": 3.1,
        "Stealth": 2.5,
        "Long Blades": 2.0,
        "Spellcasting": 0.0
      },
      "9": {
        "Stealth": 7.8,
        "Short Blades": 7.5,
        "Fighting": 5.3,
        "Dodging": 5.2,
        "Long Blades": 4.6,
        "Spellcasting": 0.0
      },
      "12": {
        "Short Blades": 11.4,
        "Stealth": 10.6,
        "Fighting": 9.2,
        "Dodging": 8.9,
        "Long Blades": 7.9,
        "Evocations": 5.6
      },
      "15": {
        "Short Blades": 14.9,
        "Fighting": 12.3,
        "Dodging": 12.2,
        "Long Blades": 10.9,
        "Stealth": 10.6,
        "Shields": 9.3
      },
      "18": {
        "Short Blades": 16.8,
        "Fighting": 14.3,
        "Dodging": 14.1,
        "Long Blades": 12.8,
        "Stealth": 10.6,
        "Shields": 10.4
      },
      "21": {
        "Short Blades": 18.3,
        "Fighting": 15.9,
        "Dodging": 15.6,
        "Long Blades": 15.2,
        "Shields": 11.2,
        "Stealth": 10.6
      },
      "27": {
        "Short Blades": 18.3,
        "Fighting": 15.9,
        "Dodging": 15.6,
        "Long Blades": 15.2,
        "Shields": 11.2,
        "Stealth": 10.6
      }
    }
  },
  "Poltergeist/Enchanter": {
    "n": 4,
    "milestones": {
      "1": {
        "Hexes": 4.4,
        "Stealth": 4.4,
        "Dodging": 2.1,
        "Spellcasting": 2.0,
        "Short Blades": 1.1,
        "Long Blades": 0.4
      },
      "3": {
        "Hexes": 4.6,
        "Stealth": 4.6,
        "Dodging": 2.3,
        "Spellcasting": 2.1,
        "Short Blades": 1.8,
        "Long Blades": 0.9
      },
      "5": {
        "Hexes": 4.9,
        "Stealth": 4.6,
        "Spellcasting": 2.3,
        "Dodging": 2.3,
        "Short Blades": 1.9,
        "Long Blades": 0.9
      },
      "7": {
        "Stealth": 6.5,
        "Hexes": 6.3,
        "Dodging": 4.5,
        "Short Blades": 4.0,
        "Spellcasting": 2.5,
        "Long Blades": 2.1
      },
      "9": {
        "Hexes": 10.0,
        "Stealth": 10.0,
        "Dodging": 4.5,
        "Short Blades": 4.0,
        "Throwing": 4.0,
        "Spellcasting": 3.2
      },
      "12": {
        "Hexes": 11.0,
        "Short Blades": 10.0,
        "Stealth": 10.0,
        "Invocations": 7.0,
        "Fighting": 6.5,
        "Dodging": 6.2
      },
      "15": {
        "Hexes": 13.0,
        "Stealth": 11.0,
        "Short Blades": 10.0,
        "Dodging": 10.0,
        "Fighting": 9.5,
        "Invocations": 8.0
      },
      "18": {
        "Hexes": 15.0,
        "Short Blades": 11.6,
        "Stealth": 11.0,
        "Dodging": 10.0,
        "Fighting": 9.5,
        "Necromancy": 9.0
      },
      "21": {
        "Hexes": 15.0,
        "Short Blades": 12.8,
        "Stealth": 12.0,
        "Fighting": 11.0,
        "Dodging": 10.0,
        "Necromancy": 9.0
      },
      "27": {
        "Hexes": 15.0,
        "Short Blades": 12.8,
        "Stealth": 12.0,
        "Fighting": 11.0,
        "Dodging": 10.0,
        "Necromancy": 9.0
      }
    }
  },
  "Kobold/Brigand": {
    "n": 4,
    "milestones": {
      "1": {
        "Stealth": 5.3,
        "Short Blades": 2.6,
        "Fighting": 2.1,
        "Throwing": 2.1,
        "Dodging": 1.2,
        "Long Blades": 0.8
      },
      "3": {
        "Stealth": 5.3,
        "Short Blades": 2.8,
        "Fighting": 2.1,
        "Throwing": 2.1,
        "Dodging": 1.2,
        "Long Blades": 0.9
      },
      "5": {
        "Stealth": 6.0,
        "Short Blades": 4.2,
        "Fighting": 2.9,
        "Throwing": 2.5,
        "Dodging": 2.2,
        "Long Blades": 1.4
      },
      "7": {
        "Stealth": 7.8,
        "Short Blades": 5.5,
        "Fighting": 3.5,
        "Dodging": 2.9,
        "Throwing": 2.5,
        "Long Blades": 1.9
      },
      "9": {
        "Stealth": 9.9,
        "Short Blades": 8.0,
        "Fighting": 5.0,
        "Dodging": 3.6,
        "Long Blades": 3.0,
        "Throwing": 2.5
      },
      "12": {
        "Stealth": 14.2,
        "Short Blades": 10.3,
        "Dodging": 8.2,
        "Fighting": 7.5,
        "Long Blades": 5.4,
        "Evocations": 2.9
      },
      "15": {
        "Stealth": 15.6,
        "Short Blades": 14.2,
        "Dodging": 11.3,
        "Fighting": 10.5,
        "Long Blades": 5.7,
        "Evocations": 2.9
      },
      "18": {
        "Stealth": 15.6,
        "Short Blades": 14.2,
        "Dodging": 11.3,
        "Fighting": 11.2,
        "Long Blades": 5.7,
        "Evocations": 2.9
      },
      "21": {
        "Stealth": 18.9,
        "Short Blades": 14.2,
        "Dodging": 11.3,
        "Fighting": 11.2,
        "Long Blades": 5.7,
        "Evocations": 2.9
      },
      "27": {
        "Stealth": 19.6,
        "Short Blades": 14.2,
        "Dodging": 11.3,
        "Fighting": 11.2,
        "Translocations": 6.8,
        "Long Blades": 5.7
      }
    }
  },
  "Demonspawn/Brigand": {
    "n": 4,
    "milestones": {
      "1": {
        "Stealth": 3.6,
        "Fighting": 2.0,
        "Throwing": 1.7,
        "Short Blades": 1.7,
        "Long Blades": 1.0,
        "Dodging": 0.9
      },
      "3": {
        "Stealth": 3.6,
        "Fighting": 2.0,
        "Throwing": 1.8,
        "Short Blades": 1.8,
        "Long Blades": 1.0,
        "Dodging": 1.0
      },
      "5": {
        "Stealth": 3.6,
        "Fighting": 2.3,
        "Short Blades": 2.3,
        "Throwing": 2.0,
        "Dodging": 1.9,
        "Armour": 1.4
      },
      "7": {
        "Stealth": 3.6,
        "Short Blades": 2.8,
        "Fighting": 2.5,
        "Dodging": 2.5,
        "Throwing": 2.2,
        "Armour": 2.0
      },
      "9": {
        "Short Blades": 6.5,
        "Dodging": 6.3,
        "Armour": 5.2,
        "Fighting": 4.2,
        "Long Blades": 3.9,
        "Throwing": 3.7
      },
      "12": {
        "Dodging": 9.4,
        "Short Blades": 8.2,
        "Armour": 7.2,
        "Invocations": 6.0,
        "Fighting": 5.8,
        "Throwing": 5.1
      },
      "15": {
        "Dodging": 9.8,
        "Short Blades": 8.2,
        "Armour": 7.2,
        "Invocations": 6.0,
        "Fighting": 5.8,
        "Throwing": 5.5
      },
      "18": {
        "Dodging": 9.8,
        "Short Blades": 8.2,
        "Armour": 7.2,
        "Invocations": 6.0,
        "Fighting": 5.8,
        "Throwing": 5.5
      },
      "21": {
        "Dodging": 9.8,
        "Short Blades": 8.2,
        "Armour": 7.2,
        "Invocations": 6.0,
        "Fighting": 5.8,
        "Throwing": 5.5
      },
      "27": {
        "Dodging": 9.8,
        "Short Blades": 8.2,
        "Armour": 7.2,
        "Invocations": 6.0,
        "Fighting": 5.8,
        "Throwing": 5.5
      }
    }
  },
  "Gargoyle/Berserker": {
    "n": 4,
    "milestones": {
      "1": {
        "Fighting": 3.3,
        "Maces & Flails": 3.0,
        "Armour": 2.2,
        "Staves": 1.7,
        "Axes": 1.6,
        "Dodging": 1.6
      },
      "3": {
        "Fighting": 3.7,
        "Maces & Flails": 3.0,
        "Armour": 2.2,
        "Axes": 1.8,
        "Staves": 1.7,
        "Dodging": 1.6
      },
      "5": {
        "Fighting": 4.4,
        "Maces & Flails": 3.0,
        "Armour": 2.3,
        "Axes": 2.1,
        "Staves": 1.7,
        "Dodging": 1.6
      },
      "7": {
        "Fighting": 5.5,
        "Armour": 4.5,
        "Maces & Flails": 3.0,
        "Axes": 2.5,
        "Dodging": 2.1,
        "Staves": 1.7
      },
      "9": {
        "Armour": 7.5,
        "Fighting": 6.9,
        "Maces & Flails": 5.7,
        "Axes": 4.5,
        "Staves": 4.3,
        "Dodging": 2.1
      },
      "12": {
        "Armour": 11.9,
        "Maces & Flails": 10.8,
        "Fighting": 10.4,
        "Axes": 8.4,
        "Polearms": 6.0,
        "Staves": 4.6
      },
      "15": {
        "Armour": 14.9,
        "Fighting": 13.4,
        "Maces & Flails": 12.7,
        "Axes": 11.3,
        "Polearms": 10.8,
        "Shields": 8.0
      },
      "18": {
        "Armour": 17.0,
        "Fighting": 15.5,
        "Maces & Flails": 13.2,
        "Axes": 13.1,
        "Polearms": 11.8,
        "Shields": 9.8
      },
      "21": {
        "Armour": 18.6,
        "Fighting": 17.2,
        "Shields": 14.7,
        "Axes": 13.8,
        "Maces & Flails": 13.4,
        "Polearms": 11.6
      },
      "27": {
        "Armour": 18.6,
        "Fighting": 17.2,
        "Shields": 14.7,
        "Axes": 13.8,
        "Maces & Flails": 13.4,
        "Polearms": 11.6
      }
    }
  },
  "Coglin/Cinder Acolyte": {
    "n": 4,
    "milestones": {
      "1": {
        "Fighting": 3.0,
        "Fire Magic": 2.6,
        "Axes": 2.4,
        "Staves": 1.6,
        "Maces & Flails": 1.5,
        "Polearms": 1.5
      },
      "3": {
        "Fighting": 3.0,
        "Axes": 2.9,
        "Fire Magic": 2.6,
        "Staves": 2.0,
        "Maces & Flails": 1.5,
        "Polearms": 1.5
      },
      "5": {
        "Polearms": 3.4,
        "Fire Magic": 3.3,
        "Fighting": 3.0,
        "Axes": 2.9,
        "Maces & Flails": 2.0,
        "Staves": 2.0
      },
      "7": {
        "Fire Magic": 3.3,
        "Fighting": 3.0,
        "Axes": 2.9,
        "Polearms": 2.9,
        "Maces & Flails": 2.0,
        "Staves": 2.0
      },
      "9": {
        "Axes": 7.2,
        "Polearms": 6.0,
        "Fighting": 5.1,
        "Staves": 3.7,
        "Maces & Flails": 3.5,
        "Fire Magic": 3.3
      },
      "12": {
        "Axes": 10.9,
        "Fighting": 8.8,
        "Polearms": 8.0,
        "Air Magic": 5.9,
        "Maces & Flails": 5.0,
        "Staves": 5.0
      },
      "15": {
        "Axes": 10.9,
        "Fighting": 9.8,
        "Polearms": 8.7,
        "Armour": 5.9,
        "Air Magic": 5.9,
        "Staves": 5.1
      },
      "18": {
        "Axes": 10.9,
        "Fighting": 9.8,
        "Polearms": 8.7,
        "Armour": 5.9,
        "Air Magic": 5.9,
        "Staves": 5.1
      },
      "21": {
        "Axes": 10.9,
        "Fighting": 9.8,
        "Polearms": 8.7,
        "Armour": 5.9,
        "Air Magic": 5.9,
        "Staves": 5.1
      },
      "27": {
        "Axes": 10.9,
        "Fighting": 9.8,
        "Polearms": 8.7,
        "Armour": 5.9,
        "Air Magic": 5.9,
        "Staves": 5.1
      }
    }
  },
  "Barachi/Conjurer": {
    "n": 4,
    "milestones": {
      "1": {
        "Conjurations": 4.3,
        "Spellcasting": 2.1,
        "Dodging": 2.1,
        "Stealth": 1.7,
        "Fighting": 1.0,
        "Maces & Flails": 0.0
      },
      "3": {
        "Conjurations": 4.7,
        "Spellcasting": 3.0,
        "Dodging": 2.1,
        "Stealth": 1.7,
        "Fighting": 1.0,
        "Maces & Flails": 0.0
      },
      "5": {
        "Conjurations": 5.3,
        "Spellcasting": 3.0,
        "Fighting": 2.5,
        "Dodging": 2.5,
        "Ranged Weapons": 2.0,
        "Stealth": 1.7
      },
      "7": {
        "Conjurations": 6.0,
        "Spellcasting": 4.5,
        "Ranged Weapons": 4.0,
        "Fighting": 3.5,
        "Dodging": 3.5,
        "Stealth": 1.7
      },
      "9": {
        "Conjurations": 9.8,
        "Spellcasting": 6.5,
        "Fighting": 5.0,
        "Dodging": 3.7,
        "Stealth": 1.7,
        "Fire Magic": 1.5
      },
      "12": {
        "Conjurations": 11.0,
        "Spellcasting": 9.9,
        "Fighting": 9.0,
        "Dodging": 9.0,
        "Ranged Weapons": 7.3,
        "Invocations": 3.0
      },
      "15": {
        "Conjurations": 13.0,
        "Dodging": 11.8,
        "Fighting": 11.5,
        "Spellcasting": 11.5,
        "Ranged Weapons": 9.0,
        "Fire Magic": 5.5
      },
      "18": {
        "Spellcasting": 13.0,
        "Conjurations": 13.0,
        "Dodging": 12.0,
        "Fighting": 11.5,
        "Ranged Weapons": 9.0,
        "Fire Magic": 5.5
      },
      "21": {
        "Spellcasting": 13.0,
        "Conjurations": 13.0,
        "Dodging": 12.0,
        "Fighting": 11.5,
        "Ranged Weapons": 11.0,
        "Fire Magic": 5.5
      },
      "27": {
        "Conjurations": 16.5,
        "Spellcasting": 13.5,
        "Dodging": 12.0,
        "Fighting": 11.5,
        "Ranged Weapons": 11.3,
        "Fire Magic": 5.5
      }
    }
  },
  "Kobold/Earth Elementalist": {
    "n": 3,
    "milestones": {
      "3": {
        "Earth Magic": 3.3,
        "Stealth": 2.7,
        "Dodging": 2.4,
        "Spellcasting": 2.3,
        "Conjurations": 1.0,
        "Short Blades": 0.1
      },
      "5": {
        "Earth Magic": 4.1,
        "Stealth": 2.7,
        "Dodging": 2.6,
        "Spellcasting": 2.3,
        "Conjurations": 1.0,
        "Fighting": 0.0
      },
      "7": {
        "Earth Magic": 4.4,
        "Stealth": 2.7,
        "Dodging": 2.6,
        "Spellcasting": 2.3,
        "Conjurations": 2.2,
        "Fighting": 0.0
      },
      "9": {
        "Earth Magic": 5.5,
        "Spellcasting": 5.0,
        "Stealth": 3.6,
        "Dodging": 3.3,
        "Conjurations": 3.2,
        "Long Blades": 0.4
      },
      "12": {
        "Dodging": 8.2,
        "Fighting": 7.6,
        "Earth Magic": 7.4,
        "Spellcasting": 7.1,
        "Alchemy": 6.0,
        "Stealth": 5.2
      },
      "15": {
        "Dodging": 8.2,
        "Fighting": 7.6,
        "Earth Magic": 7.4,
        "Spellcasting": 7.1,
        "Alchemy": 6.0,
        "Stealth": 5.2
      },
      "18": {
        "Dodging": 8.2,
        "Fighting": 7.6,
        "Earth Magic": 7.4,
        "Spellcasting": 7.1,
        "Alchemy": 6.0,
        "Stealth": 5.2
      },
      "21": {
        "Dodging": 8.2,
        "Fighting": 7.6,
        "Earth Magic": 7.4,
        "Spellcasting": 7.1,
        "Alchemy": 6.0,
        "Stealth": 5.2
      },
      "27": {
        "Dodging": 8.2,
        "Fighting": 7.6,
        "Earth Magic": 7.4,
        "Spellcasting": 7.1,
        "Alchemy": 6.0,
        "Stealth": 5.2
      }
    }
  },
  "Poltergeist/Hexslinger": {
    "n": 3,
    "milestones": {
      "1": {
        "Hexes": 4.4,
        "Dodging": 2.1,
        "Ranged Weapons": 2.0,
        "Fighting": 1.0,
        "Spellcasting": 1.0,
        "Fire Magic": 0.8
      },
      "3": {
        "Hexes": 4.4,
        "Ranged Weapons": 3.0,
        "Dodging": 2.1,
        "Spellcasting": 2.0,
        "Fighting": 1.0,
        "Fire Magic": 0.8
      },
      "5": {
        "Hexes": 6.0,
        "Ranged Weapons": 3.0,
        "Dodging": 2.2,
        "Spellcasting": 2.0,
        "Fighting": 1.0,
        "Fire Magic": 0.8
      },
      "7": {
        "Hexes": 10.0,
        "Ranged Weapons": 3.4,
        "Dodging": 3.4,
        "Spellcasting": 3.0,
        "Fighting": 2.0,
        "Fire Magic": 0.8
      },
      "9": {
        "Hexes": 10.3,
        "Dodging": 7.2,
        "Ranged Weapons": 7.0,
        "Fighting": 4.0,
        "Spellcasting": 4.0,
        "Fire Magic": 0.8
      },
      "12": {
        "Dodging": 13.0,
        "Hexes": 12.0,
        "Ranged Weapons": 11.0,
        "Fighting": 7.0,
        "Spellcasting": 4.0,
        "Invocations": 2.5
      },
      "15": {
        "Dodging": 19.5,
        "Hexes": 15.0,
        "Ranged Weapons": 13.4,
        "Fighting": 9.0,
        "Invocations": 5.5,
        "Spellcasting": 4.0
      },
      "18": {
        "Dodging": 20.7,
        "Hexes": 18.0,
        "Ranged Weapons": 13.8,
        "Fighting": 9.0,
        "Invocations": 7.5,
        "Spellcasting": 5.0
      },
      "21": {
        "Dodging": 20.7,
        "Hexes": 18.0,
        "Ranged Weapons": 16.0,
        "Fighting": 12.0,
        "Invocations": 7.5,
        "Spellcasting": 5.0
      },
      "27": {
        "Hexes": 18.0,
        "Dodging": 16.1,
        "Ranged Weapons": 16.0,
        "Fighting": 12.0,
        "Invocations": 7.5,
        "Spellcasting": 5.0
      }
    }
  },
  "Naga/Ice Elementalist": {
    "n": 2,
    "milestones": {
      "1": {
        "Ice Magic": 4.0,
        "Stealth": 3.0,
        "Spellcasting": 2.0,
        "Dodging": 1.5,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "3": {
        "Ice Magic": 4.0,
        "Stealth": 3.9,
        "Spellcasting": 2.2,
        "Dodging": 1.8,
        "Fighting": 0.0,
        "Unarmed Combat": 0.0
      },
      "5": {
        "Stealth": 4.5,
        "Ice Magic": 4.0,
        "Spellcasting": 2.4,
        "Dodging": 1.9,
        "Fighting": 0.0,
        "Maces & Flails": 0.0
      },
      "7": {
        "Stealth": 7.1,
        "Ice Magic": 4.9,
        "Spellcasting": 4.5,
        "Dodging": 3.5,
        "Long Blades": 3.1,
        "Short Blades": 1.7
      },
      "9": {
        "Stealth": 9.3,
        "Spellcasting": 6.3,
        "Ice Magic": 6.2,
        "Dodging": 4.4,
        "Long Blades": 3.2,
        "Short Blades": 2.5
      },
      "12": {
        "Stealth": 11.1,
        "Long Blades": 9.6,
        "Spellcasting": 8.0,
        "Invocations": 7.5,
        "Conjurations": 7.2,
        "Ice Magic": 7.2
      },
      "15": {
        "Stealth": 13.7,
        "Long Blades": 12.4,
        "Invocations": 10.0,
        "Fighting": 9.9,
        "Spellcasting": 9.7,
        "Alchemy": 9.0
      },
      "18": {
        "Stealth": 15.5,
        "Long Blades": 14.0,
        "Earth Magic": 11.3,
        "Fighting": 10.8,
        "Spellcasting": 10.5,
        "Invocations": 10.0
      },
      "21": {
        "Stealth": 15.5,
        "Long Blades": 14.0,
        "Earth Magic": 11.3,
        "Fighting": 10.8,
        "Spellcasting": 10.5,
        "Invocations": 10.0
      },
      "27": {
        "Stealth": 15.5,
        "Long Blades": 14.0,
        "Earth Magic": 11.3,
        "Fighting": 10.8,
        "Spellcasting": 10.5,
        "Invocations": 10.0
      }
    }
  },
  "Oni/Shapeshifter": {
    "n": 1,
    "milestones": {}
  },
  "Mummy/Gladiator": {
    "n": 1,
    "milestones": {}
  },
  "Minotaur/Chaos Knight": {
    "n": 1,
    "milestones": {}
  },
  "Felid/Shapeshifter": {
    "n": 1,
    "milestones": {}
  },
  "Gargoyle/Alchemist": {
    "n": 1,
    "milestones": {}
  }
}

// DCSS skill names in Korean, to match the (translated) in-game skill menu.
const SKILL_KO: Record<string, string> = {
  "Fighting": "전투",
  "Short Blades": "단검",
  "Long Blades": "장검",
  "Axes": "도끼",
  "Maces & Flails": "둔기",
  "Polearms": "창",
  "Staves": "지팡이",
  "Ranged Weapons": "원거리",
  "Unarmed Combat": "맨손",
  "Throwing": "투척",
  "Armour": "방어구",
  "Dodging": "회피",
  "Stealth": "은신",
  "Shields": "방패",
  "Spellcasting": "주문시전",
  "Conjurations": "파괴마법",
  "Hexes": "저주마법",
  "Summonings": "소환마법",
  "Necromancy": "강령마법",
  "Translocations": "이동마법",
  "Fire Magic": "화염마법",
  "Ice Magic": "냉기마법",
  "Air Magic": "대기마법",
  "Earth Magic": "대지마법",
  "Alchemy": "연금술",
  "Invocations": "발현",
  "Evocations": "발동",
  "Shapeshifting": "변신"
}

export function skillKo(en: string): string { return SKILL_KO[en] ?? en }
export function buildKey(species: string, background: string): string { return `${species}/${background}` }

// Species and backgrounds that appear in at least one guide — used to outline
// guided choices on the new-game selection screen. English names (the screen's
// labels are still English that early, before translation arms).
const GUIDED_NAMES = new Set<string>(Object.keys(BUILD_GUIDES).flatMap(k => k.split('/')))
export function isGuidedName(name: string): boolean { return GUIDED_NAMES.has(name.trim()) }

// Largest sample size (n) among guides that include this species/background —
// a proxy for how statistically solid the guide is. 0 = no guide. Drives the
// outline colour on the character-creation screen (more data → redder).
export function guideStrength(name: string): number {
  const nm = name.trim()
  let best = 0
  for (const [k, g] of Object.entries(BUILD_GUIDES)) {
    if (k.split('/').includes(nm)) best = Math.max(best, g.n)
  }
  return best
}

export interface RecItem { skill: string; ko: string; level: number }
export interface Rec { key: string; xl: number; items: RecItem[] }

// Recommendation is a forward TARGET: the skill levels a competent player has
// at a milestone ABOVE the player's current XL — what to train toward, not
// where they already are. Early milestones are nearly identical to the start
// skills, so we skip ahead to the first milestone whose top skill is
// meaningfully higher than the current level (and fall back to the furthest
// known milestone). null if no guide for this build.
export function recommend(species: string, background: string, xl: number, top = 4): Rec | null {
  const g = BUILD_GUIDES[buildKey(species, background)]
  if (!g) return null
  const keys = Object.keys(g.milestones).map(Number).sort((a, b) => a - b)
  if (keys.length === 0) return null
  const topLevel = (k: number): number => Math.max(...Object.values(g.milestones[String(k)]))

  const atOrBelow = keys.filter(m => m <= xl)
  const curTop = atOrBelow.length ? topLevel(atOrBelow[atOrBelow.length - 1]) : 0
  const above = keys.filter(m => m > xl)
  // Default to the furthest known milestone (the eventual goal); prefer the
  // nearest one that's a real step up from where the player is now.
  let mk = above.length ? above[above.length - 1] : keys[keys.length - 1]
  for (const m of above) {
    if (topLevel(m) > curTop + 1) { mk = m; break }
  }

  const at = g.milestones[String(mk)]
  const items = Object.entries(at).sort((a, b) => b[1] - a[1]).slice(0, top)
    .map(([skill, level]) => ({ skill, ko: skillKo(skill), level }))
  return { key: buildKey(species, background), xl: mk, items }
}
